import PDFDocument from "pdfkit";
import type { PatientProgressData } from "@shared/reports";

function collectPdfBuffer(doc: InstanceType<typeof PDFDocument>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

function sectionHeader(doc: InstanceType<typeof PDFDocument>, title: string) {
  doc.moveDown(0.5);
  doc.fontSize(13).fillColor("#0d9488").text(title);
  doc.moveDown(0.25);
  doc.fontSize(11).fillColor("#1f2937");
}

export async function generatePatientProgressPdf(data: PatientProgressData): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const bufferPromise = collectPdfBuffer(doc);

  doc.fontSize(22).fillColor("#0f766e").text("ICU Guardian AI", { align: "center" });
  doc.fontSize(14).fillColor("#374151").text("Patient Progress Report", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor("#6b7280").text(`Generated: ${data.reportDate}`, { align: "center" });
  doc.moveDown(1);

  doc.rect(50, doc.y, 495, 1).fill("#e5e7eb");
  doc.moveDown(0.75);

  doc.fontSize(11).fillColor("#111827");
  doc.text(`Patient: ${data.patientName} (${data.patientId})`);
  doc.text(`Age / Gender: ${data.age} / ${data.gender}`);
  doc.text(`Bed: ${data.bedNo}  |  Attending: ${data.doctor}`);
  doc.text(`Status: ${data.status}`);
  doc.moveDown(0.5);

  sectionHeader(doc, "Current Vitals");
  doc.text(`Heart Rate: ${data.vitals.heartRate} bpm`);
  doc.text(`SpO2: ${data.vitals.spO2}%`);
  doc.text(`Blood Pressure: ${data.vitals.bloodPressure} mmHg`);
  doc.text(`Respiratory Rate: ${data.vitals.respiratoryRate} /min`);
  doc.text(`Temperature: ${data.vitals.temperature}°F`);

  sectionHeader(doc, "Summary");
  doc.text(data.summary, { align: "justify", lineGap: 3 });

  sectionHeader(doc, "Clinical Observations");
  doc.text(data.observations, { align: "justify", lineGap: 3 });

  sectionHeader(doc, "Recommendations");
  doc.text(data.recommendations, { align: "justify", lineGap: 3 });

  sectionHeader(doc, "Active Medications");
  if (data.medications.length === 0) {
    doc.text("No active medications recorded.");
  } else {
    data.medications.forEach((med, index) => {
      doc.text(
        `${index + 1}. ${med.name} — ${med.dosage}, ${med.frequency} (${med.status})`,
        { lineGap: 2 },
      );
    });
  }

  sectionHeader(doc, "Recovery Progress Timeline");
  data.progressNotes.forEach((note, index) => {
    doc.text(`• Day ${index + 1}: ${note}`, { lineGap: 2 });
  });

  doc.moveDown(2);
  doc.fontSize(9).fillColor("#9ca3af").text(
    "This report was generated by ICU Guardian AI. For clinical decisions, consult the attending physician.",
    { align: "center" },
  );

  doc.end();
  return bufferPromise;
}

export function isPdfBuffer(buffer: Buffer): boolean {
  return buffer.length >= 4 && buffer.subarray(0, 4).toString() === "%PDF";
}
